// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/app-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool({
  name: "app_info",
  title: "App info",
  description: "Get information about the ORBIT MBBS QBANK app, its features, and available study content.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "ORBIT MBBS QBANK",
          description: "Medical education platform for MBBS students with question bank, MCQs, AI medical assistant, spaced-repetition revision, Pomodoro timer, streaks & XP.",
          url: "https://mbbsqbank-questor.lovable.app",
          features: [
            "Subject-wise question bank across MBBS subjects (Anatomy, Physiology, Biochemistry, Pathology, Pharmacology, Microbiology, Community Medicine, Forensic Medicine, ENT, Ophthalmology, Orthopaedics, Paediatrics, OBG, General Medicine, General Surgery)",
            "AI Medical Assistant chat",
            "Auto-generated MCQs from subtopics",
            "Progress tracking, streaks, XP, and leaderboard",
            "Pomodoro study timer",
            "Spaced-repetition revision queue"
          ]
        })
      }
    ]
  })
});

// src/lib/mcp/tools/list-subjects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SUBJECTS = [
  "Anatomy",
  "Physiology",
  "Biochemistry",
  "Pathology",
  "Pharmacology",
  "Microbiology",
  "Community Medicine",
  "Forensic Medicine",
  "ENT",
  "Ophthalmology",
  "Orthopaedics",
  "Paediatrics",
  "Obstetrics & Gynaecology",
  "General Medicine",
  "General Surgery"
];
var list_subjects_default = defineTool2({
  name: "list_subjects",
  title: "List subjects",
  description: "List all MBBS subjects available in the ORBIT MBBS QBANK question bank.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ subjects: SUBJECTS }) }],
    structuredContent: { subjects: SUBJECTS }
  })
});

// src/lib/mcp/tools/ask-medical-ai.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var ask_medical_ai_default = defineTool3({
  name: "ask_medical_ai",
  title: "Ask medical AI",
  description: "Ask the ORBIT MBBS QBANK medical AI assistant a question. Returns an educational answer suitable for MBBS study. Not medical advice.",
  inputSchema: {
    prompt: z.string().min(1).max(4e3).describe("The medical/study question to ask (max 4000 chars).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ prompt }) => {
    const url = "https://pmtgeydtqypwrypshhsx.supabase.co/functions/v1/ask-ai";
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt })
      });
      const data = await res.json();
      if (data.error) {
        return { content: [{ type: "text", text: data.error }], isError: true };
      }
      return {
        content: [{ type: "text", text: data.response ?? "No response" }],
        structuredContent: { response: data.response }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed to reach AI: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "orbit-mbbs-qbank-mcp",
  title: "ORBIT MBBS QBANK",
  version: "0.1.0",
  instructions: "Tools for the ORBIT MBBS QBANK medical study app. Use `app_info` to describe the app, `list_subjects` to see MBBS subjects, and `ask_medical_ai` to query the app's medical AI assistant.",
  tools: [app_info_default, list_subjects_default, ask_medical_ai_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
