import { supabase } from '@/lib/supabase';

/**
 * The client half of the `ask-gemini` contract.
 *
 * This exists because the edge function does not infer intent from the prompt
 * — it is told. `isMCQRequest` selects a completely different system prompt
 * (`index.ts` line 429: `if (isMCQsRequest)`, and `isMCQsRequest =
 * explicitMCQRequest`, assigned from the request body and from nowhere else).
 * The native app was sending prose — "Generate 10 NEET-PG style MCQs on…" —
 * with no flags at all, so every MCQ request fell through to the generic
 * branch: "You are ACEV, a helpful and knowledgeable assistant", 2000 output
 * tokens, temperature 0.7. The MCQ branch it should have hit sets 3000 tokens,
 * temperature 0.6 and a page of exact formatting rules.
 *
 * In other words, double-tap MCQs were being generated by a general-purpose
 * chatbot prompt. They came back looking plausible, which is why nothing
 * appeared broken.
 *
 * The flag derivation below mirrors src/hooks/use-ai-chat.ts in the web app, so
 * one question produces the same request from either client.
 */

/**
 * The prefixes the web app uses to mark a tap-triggered request. The function
 * strips them from the question it reasons about but still keyword-matches
 * against the raw string, so they have to be exactly these.
 */
const TRIPLE_TAP_PREFIX = 'Triple-tapped:';
const DOUBLE_TAP_PREFIX = 'Double-tapped:';

export interface Mcq {
  topic: string;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  correct: 'A' | 'B' | 'C' | 'D';
  explanation: string;
}

export interface AskResult {
  /** Prose answer. Always present, even when `mcqs` is too. */
  text: string;
  /** Parsed MCQs, when this was an MCQ request and the JSON came back valid. */
  mcqs?: Mcq[];
}

export interface HistoryEntry {
  role: 'user' | 'assistant';
  content: string;
}

/**
 * Mirrors the zod schema in the deployed function. Exceeding these is answered
 * with HTTP 200 and an `error` field, not a 4xx, so it reads as a generic
 * failure unless it is prevented here.
 */
export const MAX_PROMPT = 4000;
export const MAX_HISTORY = 20;
export const MAX_HISTORY_CONTENT = 15000;

/** What a triple tap on a question row sends. */
export function tripleTapPrompt(question: string): string {
  // "medical" in the wording is doing real work, not padding: the function
  // decides between its medical and generic system prompts by keyword-matching
  // the prompt (index.ts line 363 — 'medical', 'medicine', 'disease',
  // 'pathology', 'symptom', 'treatment', 'diagnosis', 'patient'…). An exam
  // question like "Discuss the aetiology of jaundice" contains none of them and
  // would be answered by the general-purpose assistant. Saying what the task
  // actually is happens to also select the right branch.
  return `${TRIPLE_TAP_PREFIX} Answer this MBBS medical exam question in full, as handwritten exam notes: headings, numbered points, and the clinical detail an examiner expects.\n\n${question}`;
}

/** What a double tap on a question row sends. */
export function doubleTapPrompt(topic: string): string {
  return `${DOUBLE_TAP_PREFIX} ${topic}`;
}

/**
 * Asks the function to answer as a JSON array so the result can be rendered as
 * cards rather than dumped as prose. Same shape the web app requests, so both
 * clients parse identically.
 */
function mcqPrompt(topic: string): string {
  return `Generate exactly 10 high-yield NEET PG / USMLE style MCQs on: ${topic}.

RESPOND WITH ONLY A VALID JSON ARRAY (no prose before or after, no markdown fences) of this exact shape:
[
  {
    "topic": "short topic label",
    "question": "the clinical/conceptual question",
    "options": { "A": "...", "B": "...", "C": "...", "D": "..." },
    "correct": "A",
    "explanation": "2-3 short sentences explaining the correct answer."
  }
]

Rules:
- Exactly 10 items.
- Each item must have all 4 options A-D.
- "correct" must be one of "A","B","C","D".
- Keep options concise (under 12 words each).
- Keep explanation short (under 60 words).
- Output JSON only.`;
}

/** Strips the tap prefix for display, so a bubble never shows the marker. */
export function displayText(prompt: string): string {
  return prompt
    .replace(new RegExp(`^${TRIPLE_TAP_PREFIX}\\s*`, 'i'), '')
    .replace(new RegExp(`^${DOUBLE_TAP_PREFIX}\\s*`, 'i'), '')
    .trim();
}

const MCQ_PATTERN =
  /generate\s+(?:10|ten)\s+mcqs?|create\s+(?:10|ten)\s+mcqs?|make\s+(?:10|ten)\s+mcqs?|ten\s+mcqs?|10\s+mcqs?|generate\s+mcqs?/i;
const IMPORTANT_PATTERN =
  /important question|important topics|high yield|frequently asked|commonly asked|repeated questions/i;
const CLARIFY_PATTERN =
  /i don't understand|can't understand|explain|similar|more detail/i;

/**
 * Pulls a JSON array out of a model response.
 *
 * Models add markdown fences and a sentence of preamble however firmly you ask
 * them not to, so this looks for the outermost bracket pair rather than trying
 * to parse the whole string. Anything that is not a well-formed array of items
 * with all four options returns undefined and the caller falls back to showing
 * the prose — a half-parsed quiz is worse than no quiz.
 */
export function parseMcqs(raw: string): Mcq[] | undefined {
  const start = raw.indexOf('[');
  const end = raw.lastIndexOf(']');
  if (start < 0 || end <= start) {
    return undefined;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw.slice(start, end + 1));
  } catch {
    return undefined;
  }
  if (!Array.isArray(parsed)) {
    return undefined;
  }

  const items: Mcq[] = [];
  for (const entry of parsed) {
    if (typeof entry !== 'object' || entry === null) {
      continue;
    }
    const row = entry as Record<string, unknown>;
    const options = row.options as Record<string, unknown> | undefined;
    const correct = String(row.correct ?? '').trim().toUpperCase();

    if (
      typeof row.question !== 'string' ||
      !row.question.trim() ||
      !options ||
      typeof options.A !== 'string' ||
      typeof options.B !== 'string' ||
      typeof options.C !== 'string' ||
      typeof options.D !== 'string' ||
      !['A', 'B', 'C', 'D'].includes(correct)
    ) {
      continue;
    }

    items.push({
      topic: typeof row.topic === 'string' ? row.topic : '',
      question: row.question.trim(),
      options: { A: options.A, B: options.B, C: options.C, D: options.D },
      correct: correct as Mcq['correct'],
      explanation: typeof row.explanation === 'string' ? row.explanation : '',
    });
  }

  return items.length > 0 ? items : undefined;
}

/**
 * Sends one question. Throws with a sentence worth showing the user — callers
 * put the message straight into the transcript.
 */
export async function askAi(prompt: string, history: HistoryEntry[]): Promise<AskResult> {
  const isTripleTap = new RegExp(`^${TRIPLE_TAP_PREFIX}`, 'i').test(prompt);
  const isDoubleTap = new RegExp(`^${DOUBLE_TAP_PREFIX}`, 'i').test(prompt);
  const isMCQRequest = isDoubleTap || MCQ_PATTERN.test(prompt);

  const outgoing = isMCQRequest ? mcqPrompt(displayText(prompt) || 'high-yield medical topics') : prompt;

  const { data, error } = await supabase.functions.invoke('ask-gemini', {
    body: {
      prompt: outgoing,
      conversationHistory: history,
      isTripleTap,
      isDoubleTap,
      isMCQRequest,
      isImportantQuestionsRequest: IMPORTANT_PATTERN.test(prompt),
      isNeedingClarification: CLARIFY_PATTERN.test(prompt),
    },
  });

  if (error) {
    throw new Error(error.message);
  }
  if (data?.error) {
    // Rate limiting is reported in the body with a 200. "Could not reach the
    // service" would be wrong and unhelpful when the service answered.
    throw new Error(
      data.isRateLimit
        ? `Too many questions at once. Try again in ${data.retryAfter ?? 30} seconds.`
        : String(data.error),
    );
  }

  const text = typeof data?.response === 'string' ? data.response : '';
  if (!text) {
    throw new Error('No answer came back. Try rephrasing the question.');
  }

  if (!isMCQRequest) {
    return { text };
  }

  const mcqs = parseMcqs(text);
  return mcqs
    ? { text: `${mcqs.length} practice questions.`, mcqs }
    : // The model ignored the JSON instruction. Showing its prose is better
      // than an error: the content is usually still usable MCQs, just not
      // renderable as cards.
      { text };
}
